### ISSUE TITLE
Hero field

### ISSUE THREAD

**Issue by jenstornell** [k-next/plugins#41]
I'm not sure what the image field will bring yet. Maybe we can set sizes (I hope so), but if not I like the idea of a hero plugin.

We can then get a better sense of if it will fit the content or not. It's a bit closer to the real output.

https://github.com/jenstornell/kirby-hero-field

**Comment by wottpal** [comment]
Related: https://github.com/k-next/kirby/issues/759

**Comment by bastianallgeier** [comment]
Here are a couple ideas around the core files field, that we will have: 

- there will be just a files field, not a single file field. But you will be able to set the max to 1 just like in the files section.
- it will be very similar to the files section in general. You will be able to select between list and cards layout, you will be able to set sizes, text and info and it will be sortable. The main difference is that you can select files from the current page or other pages and they will be stored in a yaml structure. 

In my opinion this would totally replace a hero field, but correct me if I'm wrong.

**Comment by wottpal** [comment]
> In my opinion this would totally replace a hero field, but correct me if I'm wrong.

Totally from a functional point of view but I guess @jenstornell's (and k-next/kirby#759
https://github.com/k-next/kirby/issues/759) focus was also about the design of the field. Maybe a `layout` option called `images` without any text would be sufficient.

**Comment by jenstornell** [comment]
@bastianallgeier @wottpal I really hope we don't need a hero field anymore.

In order for it to work is to let the image field span full width (not like the image in https://github.com/k-next/kirby/issues/759). If that works, I can deprecate my hero field and close this issue.

**Comment by jenstornell** [comment]
I just tested it. The core field `files` replaces my good old `hero` field completely. Amazing! 😄
