### ISSUE TITLE
Sync files between two or more domains

### ISSUE THREAD

**Issue by jenstornell** [k-next/plugins#56]
Anyone interested on taking over my plugin can make a comment. Stars included.

https://github.com/kirby-deprecated-plugins/kirby-sync

**Comment by bnomei** [comment]
downvoting since i will not need it and see to many limitations. if needed i would probally just sync a folder using a hook and http://flysystem.thephpleague.com/docs/

**Comment by jenstornell** [comment]
Not very big interest and I have dropped it to: https://github.com/kirby-deprecated-plugins/kirby-sync

Anyone who want can take it from there and do whatever with it.

**Comment by bnomei** [comment]
so closing this issue?

**Comment by jenstornell** [comment]
Alright. If someone what a plugin like this again, they can open a new one, or reopen this one.
